tenancy_ocid     = "<tenancy-ocid>"
user_ocid        = "<user-ocid>"
private_key_path = "<rsa-private-key-path>"
fingerprint      = "<fingerprint>"
region           = "<region-identifier>"
compartment_id   = "<tenancy-ocid>"
