- name: Configure OCI Instance
  hosts: all
  become: yes

  vars:
    docker_username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    docker_password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
    docker_image_name: "{{ lookup('env', 'DOCKER_IMAGE_NAME') }}"
    docker_image_tag_name: "{{ lookup('env', 'DOCKER_IMAGE_TAG_NAME') }}"
    instance_port: "{{ lookup('env', 'INSTANCE_PORT') }}"
    container_port: "{{ lookup('env', 'CONTAINER_PORT') }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Login to Docker registry
      shell: echo "{{ docker_password }}" | docker login --username "{{ docker_username }}" --password-stdin

    - name: Run Docker container
      shell: docker run -d -p {{ instance_port }}:{{ container_port }} --name api {{ docker_username }}/{{ docker_image_name }}:{{ docker_image_tag_name }}
